apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: actions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: actions
    app.kubernetes.io/part-of: actions
  name: actions
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: actions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: actions
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jkhelil-tenant/actions/actions@sha256:78ba7803d7c628efe18e21d3963015407a972366eb66e4493d0dff12e7b475a2
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
